version: '3.3'
services:
  db:
    image: mysql:5.7
    env_file:
      - .development.env
    restart: always
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: